moviditor/urls.py
'''define moviditor url paths'''
from django.urls import path
from . import views

app_name = 'moviditor'

urlpatterns=[
    path('', views.home, name='home'),
    path('audio', views.audio_view, name='audio'),
    path('add-audio', views.add_audio, name='add-audio'),
    path('convert-mp4/<int:audio_id>/', views.audio_to_mp4, name='convert-mp4'),
    path('video', views.video_view, name='video'),
    path('add-video', views.add_video, name='add-video'),
    path('cut-in-parts/<int:video_id>/', views.cut_into_parts, name='cut-in-parts'),
    path('confirm-del-video/<int:video_id>/<str:video_name>/', views.confirm_del_vid, name='confirm-del-vid'),
    path('del-video/<int:video_id>/<str:video_name>/', views.del_video, name='del-video'),
    path('confirm-del-audio/<int:audio_id>/<str:audio_name>', views.confirm_audio_del, name='confirm-del-aud'),
    path('del-audio/<int:audio_id>/<str:audio_name>/', views.del_audio, name='del-audio'),
    path('convert-to-mp3/<int:video_id>/<str:video_name>', views.convert_mp3, name='convert-to-mp3'),
    path('timed-cut/<int:video_id>/<str:video_name>/', views.timed_cut, name='timed-cut'),
    path('search', views.search, name='search'),
]

project_moviditor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moviditor.urls')),
    path('account/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
'''urls for the users app'''
from django.urls import path, include
from . import views
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    LoginView,
)

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(template_name='users\\templates\\registration\\logged_out.html'), name='logout'),
    path('password_reset/', PasswordResetView.as_view(template_name='users\\templates\\registration\\password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='users\\templates\\registration\\password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users\\templates\\registration\\password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='users\\templates\\registration\\password_reset_done.html'), name='password_reset_complete'),
    #registration page
    path('sign-up/', views.sign_up, name='sign-up'),
    # profile page
    path('create-profile', views.create_profile, name='create-profile'),
    path('profile/<str:username>', views.profile, name='profile')
]

moviditor/models.py
from django.db import models
from django.contrib.auth.models import User
from moviditor.logic.users_logic import get_deleted_stand_in_user
# Create your models here.

class AudioModel(models.Model):
    name = models.CharField(editable=False)
    audio = models.FileField(upload_to='audios')
    date_added = models.DateTimeField(auto_now_add=True)
    size = models.DecimalField(decimal_places=2, max_digits=10, editable=False)
    user = models.ForeignKey(User, on_delete=models.SET(get_deleted_stand_in_user), editable=False)
    class Meta:
        verbose_name = 'Audio'
    def __str__(self) -> str:
        return self.name

class ImageModel(models.Model):
    image = models.ImageField(upload_to='images')

class VideoModel(models.Model):
    name = models.CharField(editable=False)
    video = models.FileField(upload_to='videos')
    date_added = models.DateTimeField(auto_now_add=True)
    size = models.DecimalField(editable=False, decimal_places=2, max_digits=10)
    user = models.ForeignKey(User, editable=False, on_delete=models.SET(get_deleted_stand_in_user))
    class Meta:
        verbose_name = 'Video'
        verbose_name_plural = 'Videos'
    def __str__(self) -> str:
        return self.name

moviditor/forms.py
'''build forms here'''
from django import forms
from . models import AudioModel, ImageModel, VideoModel

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('widget', MultipleFileInput())
        super().__init__(*args, **kwargs)
    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(data, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result
    
class FileFieldForm(forms.Form):
    file_field = MultipleFileField()

class AudioForm(forms.ModelForm):
    class Meta:
        model = AudioModel
        fields = ['audio']
        labels = {'audio': 'Select an audio file\n'}

class ImageForm(forms.ModelForm):
    class Meta:
        model = ImageModel
        fields = ['image']
        labels = {'image': 'choose an image to use for the video:'}

class VideoForm(forms.ModelForm):
    class Meta:
        model = VideoModel
        fields = ['video']
        labels = {'video': 'upload a video:'}

moviditor/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse
import os, io, zipfile
from . models import AudioModel, VideoModel
from . forms import AudioForm, ImageForm, VideoForm
from django.contrib import messages
import numpy as np
from .logic.file_handler import get_filefield_type, del_temp_files, audio_formats, video_formats
import moviditor.logic.movie as movie
from PIL import Image
from project_moviditor.settings import MEDIA_ROOT
from moviditor.logic.password import generator as gen
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormView
from .forms import FileFieldForm
# Create your views here.

# template folder path
tpath = os.path.abspath('moviditor\\templates\\moviditor')
'''the template path'''

os.makedirs(f'{MEDIA_ROOT}\\temp_files', exist_ok=True)
w_file_path = f'{MEDIA_ROOT}\\temp_files'
'''the path to write temp files'''


def home(request):
    '''the home view'''
    return render(request, f'{tpath}\\home.html')

@login_required(redirect_field_name='next')
def audio_view(request):
    '''view for fecthing user audio files'''
    audios = AudioModel.objects.filter(user=request.user).order_by('date_added')
    context = {"audios": audios}
    return render(request, f'{tpath}\\audios.html', context)

'''# class for handling multiple file uploads/ doesn't work
class FileFieldFormView(FormView):
    form_class = FileFieldForm
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    def form_valid(self, form):
        files = form.cleaned_data['file_field']
        return (self.form_valid(), files)'''

@login_required(redirect_field_name="next")
def add_audio(request):
    '''view for uploading audio files'''
    if request.method != 'POST':
        form = AudioForm()
    else:
        form = AudioForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            audio = request.FILES['audio']
            # check if it is an audio type
            typ = get_filefield_type(audio)
            # get the extension of the file
            ext = audio.name
            ext = ext.split('.')
            ext = ext[-1]
            if 'audio' in typ and ext in audio_formats:
                new_audio = form.save(commit=False)
                new_audio.name = audio.name
                new_audio.user = request.user
                # covert audio.size(bytes) to megabytes
                byte_size = audio.size
                megabytes = np.divide(byte_size, 1_048_576)
                new_audio.size = megabytes
                new_audio.save()
                messages.success(request, f'{audio.name} has been successfully upload')
                return redirect('moviditor:audio', permanent=True)
            else:
                messages.error(request, f'{audio.name} is not a supported audio file')
                return redirect('moviditor:add-audio', permanent=True)
    context = {'form': form}
    return render(request, f'{tpath}\\add-audio.html', context)

@login_required(redirect_field_name="next")
def audio_to_mp4(request, audio_id):
    '''view for the converting audio to video, using an image'''
    audio = AudioModel.objects.get(id=audio_id)
    if request.method != 'POST':
        form = ImageForm()
    else:
        form = ImageForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            image = form.cleaned_data.get('image')
            typ = get_filefield_type(image)
            if 'image' in typ:
                sound = audio.audio.path # audio file path
                # read temp_uploaded_img file, note that image will not be saved
                img_chunks = image.chunks() # chunks generator, .read() returns empty.
                # put all chunks into a single byte
                image_byte = b''
                for chunk in img_chunks:
                    image_byte += chunk
                # covert to numpy array using PIL.Image, to use in ImageClip
                # use BytesIO to feed entire image from single byte string
                image_obj = Image.open(io.BytesIO(image_byte))
                image_obj_rbg = image_obj.convert(image_obj.mode) # convert to usable mode
                image_arr = np.array(image_obj_rbg) # feed to numpy
                # feed data into video converter
                clip = movie.video_conv(sound, image_arr)
                a_name = audio.name
                w_name = a_name.split(sep='.mp3')
                name = w_name[0] # remove extension from name
                # write a new video file
                clip.write_videofile(f'{w_file_path}\\{name}.mp4', fps=30)
                file_path2 = f'{w_file_path}\\{name}.mp4' #video path
                file = open(file_path2, 'rb') # read video
                response = HttpResponse()
                response.content = file
                response['Content-Type'] = 'video/mp4'
                response['Content-Disposition'] = f'attachment; filename={name}.mp4'
                del_temp_files(file_path2)
                return response
            else:
                messages.error(request, 'an error occured, make sure image is correct.')
                return redirect('moviditor:convert-mp4', audio_id, permanent=True)     
    context = {'form': form, 'audio': audio}
    return render(request, f'{tpath}\\convert_mp4.html', context)

@login_required(redirect_field_name="next")
def video_view(request):
    '''view for fetching user's video files'''
    videos = VideoModel.objects.filter(user=request.user).order_by('date_added')
    context = {'videos': videos}
    return render(request, f'{tpath}\\videos.html', context)

@login_required(redirect_field_name="next")
def add_video(request):
    '''view for uploading video'''
    if request.method != 'POST':
        form = VideoForm()
    else:
        form = VideoForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            video = form.cleaned_data.get('video')
            typ = get_filefield_type(video)
            # get the extension of the file
            ext = video.name
            ext = ext.split('.')
            ext = ext[-1]
            if 'video' in typ and ext in video_formats:
                new_video = form.save(commit=False)
                new_video.name = video.name
                new_video.user = request.user
                # covert size to megabytes
                byte_size = video.size
                megabytes = np.divide(byte_size, 1_048_576)
                new_video.size = megabytes
                new_video.save()
                msg = f'{video.name} was uploaded successfully'
                messages.success(request, msg)
                return redirect('moviditor:video', permanent=True)
            else:
                msg = f'{video.name} is not a supported video file'
                messages.error(request, msg)
                return redirect('moviditor:add-video', permanent=True)
    context = {'form': form}
    return render(request, f'{tpath}\\add-video.html', context)

@login_required(redirect_field_name="next")
def cut_into_parts(request, video_id):
    '''view for splitting video into parts'''
    video_obj = VideoModel.objects.get(id=video_id)
    video_file = video_obj.video.path
    if request.method == 'GET':
        context = {'video': video_obj}
        return render(request, f'{tpath}\\cut_in_parts.html', context)
    else:
        number = request.POST['number']
        number = int(number)
        # write temp part videos
        try:
            video_list = movie.split_into_parts(video_file, number)
        except OSError:
            return HttpResponse(f'Your file "{video_obj.name}" is corrupt! BITCH')
        # a byte file that will contain the zipfile to be sent to user
        byt = io.BytesIO()
        # make zipfile to store videos, each time('w')
        zf = zipfile.ZipFile(byt, 'w')
        for video in video_list:
            file_path2 = f"{w_file_path}\\{video_list.index(video)}-{gen(4)}.mp4"
            video.write_videofile(file_path2)
            flname = os.path.basename(file_path2)
            zf.write(file_path2, flname)
            del_temp_files(file_path2)
        # close zipfile outside loop, after writing files into it
        zf.close()
        response = HttpResponse()
        # then get value of byt(the zipfile) in zf
        response.content = byt.getvalue()
        zip_file_name = f'{video_obj.name} part-cuts {gen(4)}.zip'
        response['Content-Type'] = 'application/x-zip-compressed'
        response['Content-Disposition'] = f'attachment; filename={zip_file_name}'
        return response

@login_required(redirect_field_name="next")    
def convert_mp3(request, video_id, video_name):
    '''view for converting video to mp3'''
    video = VideoModel.objects.get(name=video_name, id=video_id)
    if request.method != 'POST':
        # display video to be cut in html template
        context = {'video': video}
        return render(request, f'{tpath}//convert_mp3.html', context)
    else:
        # convert the video to audio/mp3
        video_path = video.video.path
        a_name = video.name
        b_name = a_name.split(sep='.mp4')
        name = b_name[0] # remove the extension of the file name/mp4
        # write audio file
        audio = movie.mp3_conv(video=video_path)
        audio.write_audiofile(f'{w_file_path}//{name}.mp3', nbytes=4, bitrate='3000k')
        content_path = f'{w_file_path}//{name}.mp3' #path to written audio file
        file = open(content_path, 'rb')
        response = HttpResponse(content=file) #create hhtpresponse obj
        response['Content-Type'] = 'audio/mpeg'
        response['Content-Disposition'] = f'attachment; filename={name}.mp3'

moviditor/templates/moviditor/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">
  <title>moviditor</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #0a0a0a;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #9087a7;
      --bs-btn-hover-border-color: #dad4e7;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #0c0913;
      --bs-btn-active-border-color: #54a141;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="{%static 'css/navbar-fixed.css' %}" rel="stylesheet">
</head>

<body>
  <!--the preffered/current theme icons-->
  <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
      <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
      <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
      <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
      <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
  </svg>

<!--the theme toggle icon at the buttom-->
  <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
      <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
      <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
          Light
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
          Dark
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
          Auto
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
    </ul>
  </div>

<!--the fixed navbar-->
  <nav class="navbar navbar-expand-xxl navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand mx-auto" href="{% url 'moviditor:home' %}">
        <img class="d-inline-block align-text-top" src="{% static 'images/homepic.png' %}" alt="#" width="30" height="30">
        Moviditor
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'moviditor:home' %}">Home</a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link active" aria-current="page" href="{% url 'users:profile' request.user.username %}">Profile</a>
            {% else %}
            <a href="{% url 'users:login' %}" class="nav-link active">Log in</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'users:sign-up' %}" class="nav-link active">Sign up</a>
          </li>
            {% endif %}
          <li class="nav-item">
            <a href="{% url 'moviditor:audio' %}" class="nav-link active" aria-current="page">Audios</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'moviditor:video' %}" class="nav-link active" aria-current="page">Videos</a>
          </li>
        </ul>
        <form class="d-flex" role="search" action="{% url 'moviditor:search' %}" method="post">
          {% csrf_token %}
          <input class="form-control me-2" type="search" name="search-phrase" placeholder="Search name" aria-label="Search" aria-disabled="false">
          <button class="btn btn-outline-success" type="submit" aria-disabled="false">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <div class="container text">

  </div>
  <!--breadcrumbs
    <nav aria-label="breadcrumb" class="position-fixed bg-primary container-fluid">
      <ol class="breadcrumb p-3 bg-body-tertiary rounded-3">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Library</a></li>
        <li class="breadcrumb-item active" aria-current="page">Data</li>
      </ol>
    </nav>
    -->

<!--previuos navbar-->
<!--
  <nav class="navbar bg-dark navbar-expand-xxl">
    <div class="container-fluid">
        <button class="navbar-toggler bg-gradient" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="navbar-nav ml-auto">
                <a href="#" class="nav-link disabled" aria-current="page">Profile</a>
                <a href="{% url 'moviditor:audio' %}" class="nav-link active text-secondary" aria-current="page">Audios</a>
                <a href="{% url 'moviditor:video' %}" class="nav-link active text-secondary" aria-current="page">Videos</a>
            </div>
        </div>
        <a class="navbar-brand text-light mx-auto" href="{% url 'moviditor:home' %}">
            <img class="d-inline-block align-text-top" src="{% static 'images/homepic.png' %}" alt="#" width="30" height="30">
            Moviditor
        </a>
    </div>
  </nav>
  <br>
-->

{% block content %}{% endblock content %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

moviditor/templates/moviditor/videos.html
{% extends 'moviditor/base.html' %}
{% block content %}
<center>
    <h2 class="text-dark">Your Videos</h2>
    <a href="{% url 'moviditor:add-video' %}" type="button" class="btn btn-warning text-nowrap">add video</a>
</center>
<br>
{% if messages %}
    {% for msg in messages %}
        <h6 class="text-success">{{ msg }}</h6>
    {% endfor %}
{% endif %}
<hr>
{% for video in videos %}
    <ul>
        <div class="container-fluid"><video src="{{ video.video.url }}" controls height="400">not supported by browser</video></div>
        <li>{{ video.name }}</li>
        <ul>
            <li>size: {{ video.size }}mb</li>
            <li>uploaded: {{ video.date_added }}</li>
        </ul> 
        <div role="group" class="btn-group">
            <a href="#" type="button" class="btn btn-outline-danger btn-sm">cut</a>
            <a type="button" class="btn btn-outline-info btn-sm" href="{% url 'moviditor:cut-in-parts' video.id %}">divide into parts</a>
            <a href="{% url 'moviditor:convert-to-mp3' video.id video.name %}" type="button" class="btn btn-outline-warning btn-sm">convert to mp3</a>
            <a href="{% url 'moviditor:timed-cut' video.id video.name %}" type="button" class="btn btn-outline-success btn-sm">timed split</a>
        </div>
        <div role="button" class="my-3">
            <a type="button" href="{% url 'moviditor:confirm-del-vid' video.id video.name %}" class="btn btn-danger btn-sm">delete</a>
        </div>
    </ul>
    <hr><br>
{% empty %}
<h3 class="text h3">no video has been uploaded yet...</h3>
{% endfor %}
{% endblock content %}